<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TestSuiteForData</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>6140acf0-627b-4b15-8fc3-751b98748b50</testSuiteGuid>
   <testCaseLink>
      <guid>17296736-f003-4260-bf5d-36b975f09251</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Ejercicio1.1/Test_case_1-login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71ce5bb9-aef5-46da-b8b0-2be619ba83c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1f36087d-8da3-49f0-9aa0-ee7a22807588</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5bfac9fb-1612-4cc3-a042-835afceda344</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Ejercicio1.1/Test_case_2_login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e40bfac-4673-455f-93bb-7475e8f3916a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3cc95d6-6d6e-437c-a648-80eb6abb116a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fa0d527c-746f-4995-bf84-35844b16e0e8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Ejercicio1.1/Test_case_3_login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a8dfc51-ca6c-49fd-ae35-1e7b253b6dc3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a9d094a-5de7-442a-9842-7f6a6b136cb9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f6578bfa-1ae9-4f2d-9f50-55c47bf798e3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Ejercicio1.1/Test_case_4_login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>205a53d9-6474-4c9e-9095-eb7d176dad6d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aedf5c70-6076-45f1-ad8d-d00cc14a42a8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f3d5ab2b-3705-4df3-a6c5-a5ac7e7bb9d7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Ejercicio1.1/Test_case_5_login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f69549cd-43da-4548-884e-4e2d6181a79c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b4aefb65-0b95-48de-9411-388e631a7a68</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
