<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sign inNew customer Start here.Your Lis_4b978c</name>
   <tag></tag>
   <elementGuidId>2fe5f85d-bbab-44ca-976e-d45b81354a84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav-flyout-accountList</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-flyout-accountList']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-flyout-accountList</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-coreFlyout nav-flyout</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign inNew customer? Start here.Your ListsFind a Gift Create a List Save Items from the Web Wedding List Baby Wishlist Discover Your Style Explore ShowroomYour AccountYour Account Your Orders Your Lists Your Recommendations Your Subscribe &amp; Save Items Your Pets Memberships &amp; Subscriptions Register for a Business Account Manage Your Content and Devices Your Kindle Unlimited Your Music Subscriptions Your Music Your Amazon Drive Your Prime Video Your Watchlist Your Video Purchases &amp; Rentals Your Games and Software Library Your Apps &amp; Devices</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-flyout-accountList&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='nav-flyout-accountList']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-flyout-anchor']/div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&amp; Orders'])[1]/following::div[28]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Returns'])[1]/following::div[28]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'nav-flyout-accountList' and (text() = 'Sign inNew customer? Start here.Your ListsFind a Gift Create a List Save Items from the Web Wedding List Baby Wishlist Discover Your Style Explore ShowroomYour AccountYour Account Your Orders Your Lists Your Recommendations Your Subscribe &amp; Save Items Your Pets Memberships &amp; Subscriptions Register for a Business Account Manage Your Content and Devices Your Kindle Unlimited Your Music Subscriptions Your Music Your Amazon Drive Your Prime Video Your Watchlist Your Video Purchases &amp; Rentals Your Games and Software Library Your Apps &amp; Devices' or . = 'Sign inNew customer? Start here.Your ListsFind a Gift Create a List Save Items from the Web Wedding List Baby Wishlist Discover Your Style Explore ShowroomYour AccountYour Account Your Orders Your Lists Your Recommendations Your Subscribe &amp; Save Items Your Pets Memberships &amp; Subscriptions Register for a Business Account Manage Your Content and Devices Your Kindle Unlimited Your Music Subscriptions Your Music Your Amazon Drive Your Prime Video Your Watchlist Your Video Purchases &amp; Rentals Your Games and Software Library Your Apps &amp; Devices')]</value>
   </webElementXpaths>
</WebElementEntity>
